<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\ZARI.Infrastructure.csproj" />
    <ProjectReference Include="..\ServiceDefaults\ZARI.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\swagger_index.html" />
    <None Remove="Resources\swagger_style.css" />
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="Aspire.Pomelo.EntityFrameworkCore.MySql" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" />
    <PackageReference Include="FluentResults" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="OpenTelemetry.Api" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\swagger_index.html" />
    <EmbeddedResource Include="Resources\swagger_style.css" />
  </ItemGroup>
</Project>
