using System.Globalization;
using System.Text;
using ZARI.Application.Features.Loan.Reports.CicCsdf;

namespace ZARI.Api.Reporting;

/// <summary>
/// Wraps a <see cref="CicCsdfExport"/>'s already-ordered `ID`/`CI` field arrays in CIC's `HD`/`FT`
/// header/trailer and writes the whole thing as a real CSDF v1.4 submission file: pipe-delimited,
/// UTF-8 WITHOUT a byte-order mark (CIC's own validator rejects a file with one — see
/// ZARI-FE/frs/loan-cic/LoanCicContext.md §1/Troubleshooting slide), one record per line, `\r\n`
/// line endings to match the sample file in that folder. This class has zero field-order knowledge
/// of its own — it only joins and wraps what <see cref="GetCicCsdfExportQueryHandler"/> already
/// built in the correct order.
/// </summary>
public static class CicCsdfFileWriter
{
    public static byte[] Write(CicCsdfExport export)
    {
        var sb = new StringBuilder();
        var totalRecords = export.IdRecords.Count + export.CiRecords.Count;

        sb.Append(string.Join("|", "HD", export.ProviderCode, Ddmmyyyy(export.FileReferenceDate), "1.0", "0", "Generated by ZARI")).Append("\r\n");

        foreach (var record in export.IdRecords)
            sb.Append(string.Join("|", record.Select(f => f ?? string.Empty))).Append("\r\n");

        foreach (var record in export.CiRecords)
            sb.Append(string.Join("|", record.Select(f => f ?? string.Empty))).Append("\r\n");

        sb.Append(string.Join("|", "FT", export.ProviderCode, Ddmmyyyy(export.FileReferenceDate), totalRecords.ToString(CultureInfo.InvariantCulture))).Append("\r\n");

        return new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(sb.ToString());
    }

    /// The filename CIC's own spec requires: [ProviderCode]_CSDF_[YYYYMMDDhhmmss].txt — the
    /// timestamp is the file's generation time, not FileReferenceDate (which is a calendar date the
    /// data is "as of", not when the file was produced).
    public static string FileName(CicCsdfExport export, DateTimeOffset generatedAt) =>
        $"{export.ProviderCode}_CSDF_{generatedAt:yyyyMMddHHmmss}.txt";

    private static string Ddmmyyyy(DateTimeOffset date) => date.ToString("ddMMyyyy", CultureInfo.InvariantCulture);
}
