namespace ZARI.Application.Features.Customers.Update;

using ZARI.Application.Abstractions.Messaging;

public sealed record UpdateCustomerCommand(
    Guid Id,
    string Name,
    string Type,
    string Email,
    string Phone,
    string BranchId,
    string Status,
    string Owner,
    string Address,
    string? Notes,
    Guid? ArAccountId,
    int? PaymentTermsDays,
    decimal? StandingDiscountPct,
    string? MemberNo = null,
    string? Tin = null,
    string? SssOrGsisNo = null,
    DateTimeOffset? DateOfBirth = null,
    string? Sex = null,
    string? CivilStatus = null,
    int? DependentsCount = null,
    string? Employer = null,
    string? EmployerPosition = null,
    decimal? NetIncomeLastYear = null,
    DateTimeOffset? ResidenceSince = null,
    string? PriorResidenceHistory = null,
    DateTimeOffset? EmploymentSince = null,
    string? PriorEmploymentHistory = null,
    string? HousingStatus = null,
    bool OwnsVehicle = false,
    string? BankAccountInfo = null,
    string? OtherAssetsNotes = null,
    bool DataSharingConsent = false,
    DateTimeOffset? DataSharingConsentDate = null,
    string? Title = null,
    string? FirstName = null,
    string? MiddleName = null,
    string? LastName = null,
    string? Suffix = null,
    string? PlaceOfBirth = null,
    string? CountryOfBirthCode = null,
    string? NationalityCode = null,
    bool? Resident = null,
    string? AddressSubdivision = null,
    string? AddressBarangay = null,
    string? AddressCity = null,
    string? AddressProvince = null,
    string? AddressPostalCode = null,
    string? AddressCountryCode = null,
    string? AddressHouseOwnerOrLessee = null,
    DateTimeOffset? AddressOccupiedSince = null) : ICommand;
